# Form implementation generated from reading ui file 'signupv1.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QLineEdit


class Ui_SignWindow(object):
    def setupUi(self, SignWindow):
        SignWindow.setObjectName("SignWindow")
        SignWindow.resize(376, 289)
        self.centralwidget = QtWidgets.QWidget(SignWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(80, 30, 191, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(80, 80, 151, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(80, 130, 141, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        # Setting password field
        self.lineEdit_6.setEchoMode(QLineEdit.EchoMode.Password)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 10, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 60, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 110, 47, 13))
        self.label_3.setObjectName("label_3")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(80, 170, 181, 17))
        self.checkBox.setObjectName("checkBox")
        self.signupButton = QtWidgets.QPushButton(self.centralwidget)
        self.signupButton.setGeometry(QtCore.QRect(80, 210, 75, 23))
        self.signupButton.setObjectName("signupButton")
        SignWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SignWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 376, 21))
        self.menubar.setObjectName("menubar")
        SignWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SignWindow)
        self.statusbar.setObjectName("statusbar")
        SignWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SignWindow)
        QtCore.QMetaObject.connectSlotsByName(SignWindow)

    def retranslateUi(self, SignWindow):
        _translate = QtCore.QCoreApplication.translate
        SignWindow.setWindowTitle(_translate("SignWindow", "Sign Up "))
        self.label.setText(_translate("SignWindow", "E-Mail Address"))
        self.label_2.setText(_translate("SignWindow", "ID"))
        self.label_3.setText(_translate("SignWindow", "Password"))
        self.checkBox.setText(_translate("SignWindow", "I accept terms and conditions."))
        self.signupButton.setText(_translate("SignWindow", "Sign Up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SignWindow = QtWidgets.QMainWindow()
    ui = Ui_SignWindow()
    ui.setupUi(SignWindow)
    SignWindow.show()
    sys.exit(app.exec())
